### ISSUE TITLE
ChangeRequest: Bildgröße

### ISSUE THREAD

**Issue by ChrisB9** [twittwer/neo4j-paper#7]
Wie groß soll das you.png sein?

( @twittwer hab auch die todo.md angepasst, was noch zu erledigen ist )

**Comment by TrAnn3l** [comment]
Wie kann das zu groß sein? Ist 58x58px und nur 1,76kb groß.

**Comment by twittwer** [comment]
Das Bild erstreckt sich momentan über die gesamte Seite und die Frage ist, wie groß es eigentlich dargestellt werden soll

**Comment by TrAnn3l** [comment]
Geht es hier um die Ansicht im Markdown oder im fertigen PDF? Weil you.png ist im Markdown von der größe passend, während @twittwer wahrscheinlich von cypher_pattern_simple.png redet. Darum geht es aber @ChrisB9 nicht.

**Comment by kai-oswald** [comment]
Wenn es gestreckt wird einfach auf die ursprüngliche größe begrenzen? Also 58x58

**Comment by ChrisB9** [comment]
@TrAnn3l ja es geht um die fertige pdf, und glaub schon dass @twittwer das meinte :)
👍  @kai-oswald, mach ich dann auf 58x58
