### ISSUE TITLE
Abstract and Final Upload

### ISSUE THREAD

**Issue by Hurba** [twittwer/neo4j-paper#8]
@TrAnn3l & @kai-oswald 
Da @twittwer am Wochenende keine vernünftige Internetverbindung hat, dürfen wir uns eine  Verantwortlichen für den Upload der Präsi und des Abstracts kümmern.
Freiwillige vor 😆

**Comment by TrAnn3l** [comment]
Ich wähle @kai-oswald

**Comment by kai-oswald** [comment]
Damit hast du dich wohl freiwillig gemeldet 🌚

**Comment by kai-oswald** [comment]
Ist das Abstract schon vorhanden oder muss das noch geschrieben werden?
